name = "svelte-boggle"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-02-26"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[build]
command = "npm run build"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "BoggleRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BoggleRoom"]
